/* words.js — Word lists with categories and impostor hints */

var Words = (function () {
  'use strict';

  const data = {
    food: {
      name: 'Food & Drinks',
      words: [
        { word: 'Pizza', hint: 'Cheese' },
        { word: 'Sushi', hint: 'Rice' },
        { word: 'Hamburger', hint: 'Bun' },
        { word: 'Taco', hint: 'Shell' },
        { word: 'Pasta', hint: 'Noodle' },
        { word: 'Chocolate', hint: 'Cocoa' },
        { word: 'Ice Cream', hint: 'Cone' },
        { word: 'Pancake', hint: 'Syrup' },
        { word: 'Sandwich', hint: 'Bread' },
        { word: 'Steak', hint: 'Grill' },
        { word: 'Salad', hint: 'Lettuce' },
        { word: 'Soup', hint: 'Bowl' },
        { word: 'Popcorn', hint: 'Movie' },
        { word: 'Donut', hint: 'Sprinkles' },
        { word: 'Waffle', hint: 'Breakfast' },
        { word: 'Burrito', hint: 'Wrap' },
        { word: 'Cupcake', hint: 'Frosting' },
        { word: 'Pretzel', hint: 'Salt' },
        { word: 'Bacon', hint: 'Pork' },
        { word: 'Omelette', hint: 'Egg' },
        { word: 'French Fries', hint: 'Potato' },
        { word: 'Cheesecake', hint: 'Dessert' },
        { word: 'Lasagna', hint: 'Layers' },
        { word: 'Cereal', hint: 'Milk' },
        { word: 'Croissant', hint: 'Butter' },
        { word: 'Smoothie', hint: 'Blend' },
        { word: 'Coffee', hint: 'Bean' },
        { word: 'Lemonade', hint: 'Citrus' },
        { word: 'Milkshake', hint: 'Straw' },
        { word: 'Hot Dog', hint: 'Mustard' },
        { word: 'Brownie', hint: 'Fudge' },
        { word: 'Muffin', hint: 'Blueberry' },
        { word: 'Curry', hint: 'Spice' },
        { word: 'Ramen', hint: 'Broth' },
        { word: 'Avocado', hint: 'Green' },
        { word: 'Honey', hint: 'Bee' },
        { word: 'Peanut Butter', hint: 'Jelly' },
        { word: 'Nachos', hint: 'Chips' },
        { word: 'Mango', hint: 'Tropical' },
        { word: 'Cinnamon Roll', hint: 'Icing' },
        { word: 'Fried Rice', hint: 'Wok' },
        { word: 'Garlic Bread', hint: 'Toast' },
        { word: 'Macaroni', hint: 'Elbow' },
        { word: 'Pumpkin Pie', hint: 'Autumn' },
        { word: 'Cotton Candy', hint: 'Fair' },
        { word: 'Spaghetti', hint: 'Meatball' },
        { word: 'Grape', hint: 'Vine' },
        { word: 'Watermelon', hint: 'Seeds' },
        { word: 'Pickle', hint: 'Cucumber' },
        { word: 'Marshmallow', hint: 'Campfire' },
        { word: 'Lobster', hint: 'Claw' },
        { word: 'Dumpling', hint: 'Steam' },
        { word: 'Boba Tea', hint: 'Tapioca' },
        { word: 'Churro', hint: 'Sugar' },
        { word: 'Fondue', hint: 'Dip' },
        { word: 'Granola', hint: 'Oats' },
        { word: 'Hummus', hint: 'Chickpea' },
        { word: 'Tiramisu', hint: 'Espresso' },
        { word: 'Guacamole', hint: 'Avocado' },
        { word: 'Clam Chowder', hint: 'Creamy' }
      ]
    },
    animals: {
      name: 'Animals',
      words: [
        { word: 'Dolphin', hint: 'Ocean' },
        { word: 'Elephant', hint: 'Trunk' },
        { word: 'Penguin', hint: 'Ice' },
        { word: 'Giraffe', hint: 'Neck' },
        { word: 'Lion', hint: 'Mane' },
        { word: 'Butterfly', hint: 'Wings' },
        { word: 'Octopus', hint: 'Tentacle' },
        { word: 'Kangaroo', hint: 'Pouch' },
        { word: 'Parrot', hint: 'Talk' },
        { word: 'Turtle', hint: 'Shell' },
        { word: 'Wolf', hint: 'Pack' },
        { word: 'Eagle', hint: 'Soar' },
        { word: 'Shark', hint: 'Fin' },
        { word: 'Panda', hint: 'Bamboo' },
        { word: 'Chameleon', hint: 'Color' },
        { word: 'Hummingbird', hint: 'Hover' },
        { word: 'Cheetah', hint: 'Speed' },
        { word: 'Owl', hint: 'Night' },
        { word: 'Flamingo', hint: 'Pink' },
        { word: 'Gorilla', hint: 'Chest' },
        { word: 'Seahorse', hint: 'Coral' },
        { word: 'Koala', hint: 'Eucalyptus' },
        { word: 'Polar Bear', hint: 'Arctic' },
        { word: 'Jellyfish', hint: 'Sting' },
        { word: 'Peacock', hint: 'Feather' },
        { word: 'Bat', hint: 'Cave' },
        { word: 'Fox', hint: 'Clever' },
        { word: 'Hedgehog', hint: 'Spines' },
        { word: 'Whale', hint: 'Deep' },
        { word: 'Crocodile', hint: 'Swamp' },
        { word: 'Sloth', hint: 'Slow' },
        { word: 'Frog', hint: 'Leap' },
        { word: 'Zebra', hint: 'Stripes' },
        { word: 'Hamster', hint: 'Wheel' },
        { word: 'Crab', hint: 'Pinch' },
        { word: 'Toucan', hint: 'Beak' },
        { word: 'Scorpion', hint: 'Tail' },
        { word: 'Moose', hint: 'Antlers' },
        { word: 'Squirrel', hint: 'Acorn' },
        { word: 'Pelican', hint: 'Scoop' },
        { word: 'Starfish', hint: 'Tide' },
        { word: 'Raccoon', hint: 'Mask' },
        { word: 'Caterpillar', hint: 'Cocoon' },
        { word: 'Llama', hint: 'Spit' },
        { word: 'Porcupine', hint: 'Quill' },
        { word: 'Armadillo', hint: 'Armor' },
        { word: 'Goldfish', hint: 'Bowl' },
        { word: 'Swan', hint: 'Lake' },
        { word: 'Ladybug', hint: 'Spots' },
        { word: 'Beaver', hint: 'Dam' },
        { word: 'Stingray', hint: 'Flat' },
        { word: 'Mongoose', hint: 'Snake' },
        { word: 'Firefly', hint: 'Glow' },
        { word: 'Narwhal', hint: 'Horn' },
        { word: 'Meerkat', hint: 'Lookout' },
        { word: 'Axolotl', hint: 'Gills' },
        { word: 'Iguana', hint: 'Lizard' },
        { word: 'Chinchilla', hint: 'Fur' },
        { word: 'Mantis', hint: 'Praying' },
        { word: 'Otter', hint: 'River' }
      ]
    },
    objects: {
      name: 'Everyday Objects',
      words: [
        { word: 'Umbrella', hint: 'Rain' },
        { word: 'Backpack', hint: 'School' },
        { word: 'Candle', hint: 'Flame' },
        { word: 'Mirror', hint: 'Reflection' },
        { word: 'Pillow', hint: 'Sleep' },
        { word: 'Scissors', hint: 'Cut' },
        { word: 'Wallet', hint: 'Money' },
        { word: 'Toothbrush', hint: 'Teeth' },
        { word: 'Sunglasses', hint: 'Shade' },
        { word: 'Key', hint: 'Lock' },
        { word: 'Clock', hint: 'Time' },
        { word: 'Blanket', hint: 'Warm' },
        { word: 'Headphones', hint: 'Music' },
        { word: 'Lamp', hint: 'Light' },
        { word: 'Calendar', hint: 'Date' },
        { word: 'Notebook', hint: 'Write' },
        { word: 'Stapler', hint: 'Office' },
        { word: 'Battery', hint: 'Power' },
        { word: 'Zipper', hint: 'Jacket' },
        { word: 'Lighter', hint: 'Fire' },
        { word: 'Doorbell', hint: 'Ring' },
        { word: 'Sponge', hint: 'Soak' },
        { word: 'Eraser', hint: 'Pencil' },
        { word: 'Thermos', hint: 'Hot' },
        { word: 'Compass', hint: 'North' },
        { word: 'Paperclip', hint: 'Attach' },
        { word: 'Broom', hint: 'Sweep' },
        { word: 'Rubber Band', hint: 'Stretch' },
        { word: 'Magnifying Glass', hint: 'Zoom' },
        { word: 'Whistle', hint: 'Blow' },
        { word: 'Plunger', hint: 'Clog' },
        { word: 'Alarm Clock', hint: 'Morning' },
        { word: 'Bookmark', hint: 'Page' },
        { word: 'Flashlight', hint: 'Dark' },
        { word: 'Coaster', hint: 'Drink' },
        { word: 'Tape', hint: 'Stick' },
        { word: 'Corkscrew', hint: 'Wine' },
        { word: 'Clothespin', hint: 'Hang' },
        { word: 'Ruler', hint: 'Measure' },
        { word: 'Dice', hint: 'Roll' },
        { word: 'Soap', hint: 'Wash' },
        { word: 'Stamp', hint: 'Mail' },
        { word: 'Thimble', hint: 'Sew' },
        { word: 'Funnel', hint: 'Pour' },
        { word: 'Padlock', hint: 'Secure' },
        { word: 'Whisk', hint: 'Stir' },
        { word: 'Ladle', hint: 'Scoop' },
        { word: 'Mop', hint: 'Floor' },
        { word: 'Pliers', hint: 'Grip' },
        { word: 'Wrench', hint: 'Bolt' }
      ]
    },
    places: {
      name: 'Places',
      words: [
        { word: 'Airport', hint: 'Travel' },
        { word: 'Beach', hint: 'Sand' },
        { word: 'Library', hint: 'Books' },
        { word: 'Hospital', hint: 'Doctor' },
        { word: 'Museum', hint: 'Art' },
        { word: 'Restaurant', hint: 'Menu' },
        { word: 'Gym', hint: 'Workout' },
        { word: 'Movie Theater', hint: 'Screen' },
        { word: 'Park', hint: 'Bench' },
        { word: 'School', hint: 'Teacher' },
        { word: 'Mall', hint: 'Shopping' },
        { word: 'Zoo', hint: 'Cage' },
        { word: 'Bank', hint: 'Vault' },
        { word: 'Stadium', hint: 'Crowd' },
        { word: 'Church', hint: 'Prayer' },
        { word: 'Gas Station', hint: 'Fuel' },
        { word: 'Amusement Park', hint: 'Ride' },
        { word: 'Farm', hint: 'Barn' },
        { word: 'Aquarium', hint: 'Fish' },
        { word: 'Casino', hint: 'Gamble' },
        { word: 'Lighthouse', hint: 'Beacon' },
        { word: 'Laundromat', hint: 'Wash' },
        { word: 'Bakery', hint: 'Oven' },
        { word: 'Cemetery', hint: 'Grave' },
        { word: 'Subway', hint: 'Underground' },
        { word: 'Bowling Alley', hint: 'Pins' },
        { word: 'Barbershop', hint: 'Haircut' },
        { word: 'Planetarium', hint: 'Stars' },
        { word: 'Courthouse', hint: 'Judge' },
        { word: 'Spa', hint: 'Relax' },
        { word: 'Ski Resort', hint: 'Slope' },
        { word: 'Warehouse', hint: 'Storage' },
        { word: 'Post Office', hint: 'Letter' },
        { word: 'Campsite', hint: 'Tent' },
        { word: 'Fire Station', hint: 'Alarm' },
        { word: 'Nightclub', hint: 'Dance' },
        { word: 'Rooftop', hint: 'View' },
        { word: 'Pharmacy', hint: 'Medicine' },
        { word: 'Junkyard', hint: 'Scrap' },
        { word: 'Observatory', hint: 'Telescope' },
        { word: 'Greenhouse', hint: 'Plants' },
        { word: 'Dock', hint: 'Boat' },
        { word: 'Elevator', hint: 'Floor' },
        { word: 'Treehouse', hint: 'Climb' },
        { word: 'Cave', hint: 'Dark' },
        { word: 'Volcano', hint: 'Lava' },
        { word: 'Waterfall', hint: 'Cascade' },
        { word: 'Oasis', hint: 'Desert' },
        { word: 'Igloo', hint: 'Snow' },
        { word: 'Dungeon', hint: 'Castle' }
      ]
    },
    activities: {
      name: 'Activities',
      words: [
        { word: 'Camping', hint: 'Outdoors' },
        { word: 'Cooking', hint: 'Kitchen' },
        { word: 'Dancing', hint: 'Music' },
        { word: 'Painting', hint: 'Canvas' },
        { word: 'Fishing', hint: 'Rod' },
        { word: 'Gardening', hint: 'Plant' },
        { word: 'Hiking', hint: 'Trail' },
        { word: 'Yoga', hint: 'Pose' },
        { word: 'Photography', hint: 'Shutter' },
        { word: 'Ice Skating', hint: 'Rink' },
        { word: 'Horseback Riding', hint: 'Saddle' },
        { word: 'Knitting', hint: 'Yarn' },
        { word: 'Scuba Diving', hint: 'Tank' },
        { word: 'Bungee Jumping', hint: 'Cord' },
        { word: 'Rock Climbing', hint: 'Harness' },
        { word: 'Bird Watching', hint: 'Binoculars' },
        { word: 'Whittling', hint: 'Knife' },
        { word: 'Pottery', hint: 'Clay' },
        { word: 'Canoeing', hint: 'Paddle' },
        { word: 'Juggling', hint: 'Balls' },
        { word: 'Origami', hint: 'Fold' },
        { word: 'Meditation', hint: 'Calm' },
        { word: 'Sledding', hint: 'Hill' },
        { word: 'Skydiving', hint: 'Parachute' },
        { word: 'Scrapbooking', hint: 'Glue' },
        { word: 'Trivia', hint: 'Questions' },
        { word: 'Stargazing', hint: 'Night' },
        { word: 'Rollerblading', hint: 'Wheels' },
        { word: 'Treasure Hunt', hint: 'Map' },
        { word: 'Arm Wrestling', hint: 'Strength' },
        { word: 'Trampolining', hint: 'Bounce' },
        { word: 'Volunteering', hint: 'Help' },
        { word: 'Woodworking', hint: 'Carve' },
        { word: 'Parkour', hint: 'Jump' },
        { word: 'Composting', hint: 'Soil' },
        { word: 'Beekeeping', hint: 'Hive' },
        { word: 'Calligraphy', hint: 'Ink' },
        { word: 'Tai Chi', hint: 'Flow' },
        { word: 'Geocaching', hint: 'GPS' },
        { word: 'Astronomy', hint: 'Stars' }
      ]
    },
    jobs: {
      name: 'Jobs',
      words: [
        { word: 'Firefighter', hint: 'Emergency' },
        { word: 'Pilot', hint: 'Cockpit' },
        { word: 'Chef', hint: 'Kitchen' },
        { word: 'Dentist', hint: 'Teeth' },
        { word: 'Astronaut', hint: 'Space' },
        { word: 'Detective', hint: 'Clue' },
        { word: 'Lifeguard', hint: 'Pool' },
        { word: 'Journalist', hint: 'News' },
        { word: 'Mechanic', hint: 'Engine' },
        { word: 'Magician', hint: 'Trick' },
        { word: 'Plumber', hint: 'Pipe' },
        { word: 'Electrician', hint: 'Wire' },
        { word: 'Veterinarian', hint: 'Animal' },
        { word: 'Carpenter', hint: 'Wood' },
        { word: 'Archaeologist', hint: 'Dig' },
        { word: 'Florist', hint: 'Flower' },
        { word: 'Barista', hint: 'Coffee' },
        { word: 'Librarian', hint: 'Book' },
        { word: 'Surgeon', hint: 'Operate' },
        { word: 'Farmer', hint: 'Harvest' },
        { word: 'Photographer', hint: 'Lens' },
        { word: 'Taxi Driver', hint: 'Meter' },
        { word: 'Zookeeper', hint: 'Cage' },
        { word: 'Blacksmith', hint: 'Forge' },
        { word: 'DJ', hint: 'Turntable' },
        { word: 'Translator', hint: 'Language' },
        { word: 'Locksmith', hint: 'Key' },
        { word: 'Sommelier', hint: 'Wine' },
        { word: 'Referee', hint: 'Whistle' },
        { word: 'Cartographer', hint: 'Map' },
        { word: 'Beekeeper', hint: 'Honey' },
        { word: 'Auctioneer', hint: 'Bid' },
        { word: 'Stunt Double', hint: 'Action' },
        { word: 'Midwife', hint: 'Birth' },
        { word: 'Taxidermist', hint: 'Mount' },
        { word: 'Jeweler', hint: 'Gem' },
        { word: 'Tailor', hint: 'Fabric' },
        { word: 'Butler', hint: 'Serve' },
        { word: 'Gondolier', hint: 'Venice' },
        { word: 'Puppeteer', hint: 'String' }
      ]
    },
    sports: {
      name: 'Sports',
      words: [
        { word: 'Basketball', hint: 'Court' },
        { word: 'Soccer', hint: 'Goal' },
        { word: 'Tennis', hint: 'Racket' },
        { word: 'Baseball', hint: 'Diamond' },
        { word: 'Swimming', hint: 'Lane' },
        { word: 'Golf', hint: 'Club' },
        { word: 'Hockey', hint: 'Puck' },
        { word: 'Boxing', hint: 'Ring' },
        { word: 'Volleyball', hint: 'Net' },
        { word: 'Wrestling', hint: 'Mat' },
        { word: 'Gymnastics', hint: 'Beam' },
        { word: 'Cricket', hint: 'Wicket' },
        { word: 'Rugby', hint: 'Scrum' },
        { word: 'Table Tennis', hint: 'Paddle' },
        { word: 'Badminton', hint: 'Shuttle' },
        { word: 'Polo', hint: 'Horse' },
        { word: 'Lacrosse', hint: 'Stick' },
        { word: 'Curling', hint: 'Stone' },
        { word: 'Rowing', hint: 'Oar' },
        { word: 'Archery', hint: 'Target' },
        { word: 'Fencing', hint: 'Epee' },
        { word: 'Softball', hint: 'Pitch' },
        { word: 'Dodgeball', hint: 'Throw' },
        { word: 'Marathon', hint: 'Distance' },
        { word: 'Surfing', hint: 'Board' },
        { word: 'Skiing', hint: 'Slope' },
        { word: 'Snowboarding', hint: 'Halfpipe' },
        { word: 'Kayaking', hint: 'Rapids' },
        { word: 'Triathlon', hint: 'Three' },
        { word: 'Figure Skating', hint: 'Spin' },
        { word: 'Water Polo', hint: 'Pool' },
        { word: 'Sumo', hint: 'Japan' },
        { word: 'Javelin', hint: 'Spear' },
        { word: 'High Jump', hint: 'Bar' },
        { word: 'Bobsled', hint: 'Track' },
        { word: 'Shot Put', hint: 'Heavy' },
        { word: 'Hurdles', hint: 'Jump' },
        { word: 'Darts', hint: 'Bullseye' },
        { word: 'Skateboarding', hint: 'Trick' },
        { word: 'Handball', hint: 'Pass' }
      ]
    },
    movies: {
      name: 'Movies & TV',
      words: [
        { word: 'Star Wars', hint: 'Space' },
        { word: 'Harry Potter', hint: 'Wizard' },
        { word: 'Jurassic Park', hint: 'Dinosaur' },
        { word: 'The Lion King', hint: 'Pride' },
        { word: 'Finding Nemo', hint: 'Fish' },
        { word: 'Spider-Man', hint: 'Web' },
        { word: 'Frozen', hint: 'Ice' },
        { word: 'Shrek', hint: 'Ogre' },
        { word: 'Batman', hint: 'Gotham' },
        { word: 'Toy Story', hint: 'Woody' },
        { word: 'The Matrix', hint: 'Pill' },
        { word: 'Titanic', hint: 'Ship' },
        { word: 'Jaws', hint: 'Shark' },
        { word: 'Indiana Jones', hint: 'Whip' },
        { word: 'Ghostbusters', hint: 'Slime' },
        { word: 'Back to the Future', hint: 'DeLorean' },
        { word: 'The Wizard of Oz', hint: 'Dorothy' },
        { word: 'Aladdin', hint: 'Genie' },
        { word: 'Rocky', hint: 'Boxing' },
        { word: 'Pinocchio', hint: 'Nose' },
        { word: 'Breaking Bad', hint: 'Chemistry' },
        { word: 'Game of Thrones', hint: 'Dragon' },
        { word: 'Stranger Things', hint: 'Upside Down' },
        { word: 'The Office', hint: 'Paper' },
        { word: 'Friends', hint: 'Couch' },
        { word: 'Squid Game', hint: 'Games' },
        { word: 'The Simpsons', hint: 'Yellow' },
        { word: 'SpongeBob', hint: 'Pineapple' },
        { word: 'Scooby-Doo', hint: 'Mystery' },
        { word: 'Willy Wonka', hint: 'Chocolate' },
        { word: 'The Godfather', hint: 'Mafia' },
        { word: 'E.T.', hint: 'Phone' },
        { word: 'Despicable Me', hint: 'Minion' },
        { word: 'The Incredibles', hint: 'Super' },
        { word: 'Ratatouille', hint: 'Chef' },
        { word: 'Avatar', hint: 'Blue' },
        { word: 'Pokémon', hint: 'Catch' },
        { word: 'Mario', hint: 'Mushroom' },
        { word: 'Hunger Games', hint: 'Arena' },
        { word: 'Jumanji', hint: 'Jungle' }
      ]
    },
    countries: {
      name: 'Countries & Cities',
      words: [
        { word: 'Paris', hint: 'Europe' },
        { word: 'Tokyo', hint: 'Asia' },
        { word: 'New York', hint: 'Skyscraper' },
        { word: 'Egypt', hint: 'Pyramid' },
        { word: 'Brazil', hint: 'Carnival' },
        { word: 'Australia', hint: 'Outback' },
        { word: 'London', hint: 'Bridge' },
        { word: 'Italy', hint: 'Pasta' },
        { word: 'Hawaii', hint: 'Island' },
        { word: 'Mexico', hint: 'Fiesta' },
        { word: 'India', hint: 'Spice' },
        { word: 'Canada', hint: 'Maple' },
        { word: 'China', hint: 'Wall' },
        { word: 'Jamaica', hint: 'Reggae' },
        { word: 'Greece', hint: 'Ruins' },
        { word: 'Switzerland', hint: 'Alps' },
        { word: 'Russia', hint: 'Kremlin' },
        { word: 'Las Vegas', hint: 'Casino' },
        { word: 'Iceland', hint: 'Geyser' },
        { word: 'Dubai', hint: 'Luxury' },
        { word: 'Venice', hint: 'Canal' },
        { word: 'Amsterdam', hint: 'Bicycle' },
        { word: 'Morocco', hint: 'Market' },
        { word: 'Thailand', hint: 'Temple' },
        { word: 'Kenya', hint: 'Safari' },
        { word: 'Norway', hint: 'Fjord' },
        { word: 'Peru', hint: 'Inca' },
        { word: 'Cuba', hint: 'Cigar' },
        { word: 'Seoul', hint: 'K-Pop' },
        { word: 'Ireland', hint: 'Clover' },
        { word: 'Hollywood', hint: 'Film' },
        { word: 'Antarctica', hint: 'Penguin' },
        { word: 'Singapore', hint: 'Garden' },
        { word: 'Nashville', hint: 'Country' },
        { word: 'Bermuda', hint: 'Triangle' },
        { word: 'Monaco', hint: 'Grand Prix' },
        { word: 'Vatican', hint: 'Pope' },
        { word: 'Transylvania', hint: 'Vampire' },
        { word: 'Area 51', hint: 'Alien' },
        { word: 'Atlantis', hint: 'Myth' }
      ]
    },
    technology: {
      name: 'Technology',
      words: [
        { word: 'Smartphone', hint: 'Screen' },
        { word: 'Robot', hint: 'Machine' },
        { word: 'Wi-Fi', hint: 'Signal' },
        { word: 'Laptop', hint: 'Keyboard' },
        { word: 'GPS', hint: 'Navigate' },
        { word: 'Bluetooth', hint: 'Wireless' },
        { word: 'Drone', hint: 'Fly' },
        { word: 'Virtual Reality', hint: 'Headset' },
        { word: 'Selfie', hint: 'Camera' },
        { word: 'Emoji', hint: 'Face' },
        { word: 'Hashtag', hint: 'Trend' },
        { word: 'Password', hint: 'Secret' },
        { word: 'Algorithm', hint: 'Code' },
        { word: 'Bitcoin', hint: 'Crypto' },
        { word: 'Podcast', hint: 'Audio' },
        { word: 'Meme', hint: 'Viral' },
        { word: 'Firewall', hint: 'Security' },
        { word: 'Cloud', hint: 'Storage' },
        { word: 'Pixel', hint: 'Dot' },
        { word: 'USB', hint: 'Plug' },
        { word: 'Satellite', hint: 'Orbit' },
        { word: 'Hologram', hint: 'Light' },
        { word: 'Printer', hint: 'Paper' },
        { word: 'Microchip', hint: 'Silicon' },
        { word: 'Solar Panel', hint: 'Sun' },
        { word: 'Webcam', hint: 'Video' },
        { word: 'Joystick', hint: 'Game' },
        { word: 'Hard Drive', hint: 'Data' },
        { word: 'Router', hint: 'Internet' },
        { word: 'Touchscreen', hint: 'Tap' },
        { word: 'Smartwatch', hint: 'Wrist' },
        { word: 'QR Code', hint: 'Scan' },
        { word: 'Streaming', hint: 'Watch' },
        { word: '3D Printer', hint: 'Layer' },
        { word: 'Deepfake', hint: 'Fake' },
        { word: 'Chatbot', hint: 'Reply' },
        { word: 'Cybersecurity', hint: 'Hack' },
        { word: 'Fiber Optic', hint: 'Fast' },
        { word: 'NFC', hint: 'Contactless' },
        { word: 'LED', hint: 'Bright' }
      ]
    },
    music: {
      name: 'Music',
      words: [
        { word: 'Guitar', hint: 'Strings' },
        { word: 'Piano', hint: 'Keys' },
        { word: 'Drums', hint: 'Beat' },
        { word: 'Violin', hint: 'Bow' },
        { word: 'Trumpet', hint: 'Brass' },
        { word: 'Microphone', hint: 'Sing' },
        { word: 'Cello', hint: 'Deep' },
        { word: 'Concert', hint: 'Stage' },
        { word: 'Jazz', hint: 'Saxophone' },
        { word: 'Opera', hint: 'Voice' },
        { word: 'Rap', hint: 'Rhyme' },
        { word: 'Ukulele', hint: 'Hawaii' },
        { word: 'Harmonica', hint: 'Blues' },
        { word: 'Banjo', hint: 'Country' },
        { word: 'Flute', hint: 'Wind' },
        { word: 'Choir', hint: 'Harmony' },
        { word: 'Lullaby', hint: 'Sleep' },
        { word: 'Tambourine', hint: 'Shake' },
        { word: 'Orchestra', hint: 'Conductor' },
        { word: 'Jukebox', hint: 'Coin' },
        { word: 'Vinyl', hint: 'Record' },
        { word: 'Karaoke', hint: 'Lyrics' },
        { word: 'Bagpipe', hint: 'Scotland' },
        { word: 'Metronome', hint: 'Tempo' },
        { word: 'Encore', hint: 'Again' },
        { word: 'Duet', hint: 'Two' },
        { word: 'Remix', hint: 'Version' },
        { word: 'Bassoon', hint: 'Reed' },
        { word: 'Xylophone', hint: 'Mallet' },
        { word: 'Acapella', hint: 'Unaccompanied' }
      ]
    },
    abstract: {
      name: 'Abstract / Hard',
      words: [
        { word: 'Nostalgia', hint: 'Memory' },
        { word: 'Déjà Vu', hint: 'Repeat' },
        { word: 'Karma', hint: 'Balance' },
        { word: 'Gravity', hint: 'Fall' },
        { word: 'Time', hint: 'Clock' },
        { word: 'Dream', hint: 'Sleep' },
        { word: 'Freedom', hint: 'Liberty' },
        { word: 'Luck', hint: 'Chance' },
        { word: 'Silence', hint: 'Quiet' },
        { word: 'Shadow', hint: 'Light' },
        { word: 'Echo', hint: 'Sound' },
        { word: 'Chaos', hint: 'Disorder' },
        { word: 'Irony', hint: 'Opposite' },
        { word: 'Adrenaline', hint: 'Rush' },
        { word: 'Instinct', hint: 'Gut' },
        { word: 'Infinity', hint: 'Forever' },
        { word: 'Paradox', hint: 'Contradiction' },
        { word: 'Illusion', hint: 'Trick' },
        { word: 'Momentum', hint: 'Force' },
        { word: 'Taboo', hint: 'Forbidden' },
        { word: 'Ego', hint: 'Self' },
        { word: 'Entropy', hint: 'Decay' },
        { word: 'Empathy', hint: 'Feel' },
        { word: 'Sarcasm', hint: 'Tone' },
        { word: 'Conscience', hint: 'Moral' },
        { word: 'Vertigo', hint: 'Dizzy' },
        { word: 'Wanderlust', hint: 'Travel' },
        { word: 'Serendipity', hint: 'Happy' },
        { word: 'Euphoria', hint: 'Joy' },
        { word: 'Dread', hint: 'Fear' }
      ]
    },
    brainrot: {
      name: 'Brain Rot',
      words: [
        { word: 'Skibidi', hint: 'Toilet' },
        { word: 'Rizz', hint: 'Charm' },
        { word: 'Gyatt', hint: 'Reaction' },
        { word: 'Sigma', hint: 'Grindset' },
        { word: 'Mewing', hint: 'Jawline' },
        { word: 'Fanum Tax', hint: 'Steal' },
        { word: 'Ohio', hint: 'Cursed' },
        { word: 'Edging', hint: 'Almost' },
        { word: 'Gooning', hint: 'Zone' },
        { word: 'Bussin', hint: 'Delicious' },
        { word: 'No Cap', hint: 'Truth' },
        { word: 'Slay', hint: 'Queen' },
        { word: 'Bet', hint: 'Agree' },
        { word: 'Ick', hint: 'Turnoff' },
        { word: 'Simp', hint: 'Obsessed' },
        { word: 'NPC', hint: 'Scripted' },
        { word: 'Main Character', hint: 'Energy' },
        { word: 'Delulu', hint: 'Delusional' },
        { word: 'Ate', hint: 'Killed it' },
        { word: 'Snatched', hint: 'Flawless' },
        { word: 'Era', hint: 'Phase' },
        { word: 'Rent Free', hint: 'Mind' },
        { word: 'Gaslighting', hint: 'Manipulate' },
        { word: 'Beige Flag', hint: 'Weird' },
        { word: 'Understood the Assignment', hint: 'Nailed' },
        { word: 'Cheugy', hint: 'Outdated' },
        { word: 'Yeet', hint: 'Throw' },
        { word: 'Vibe Check', hint: 'Mood' },
        { word: 'Lowkey', hint: 'Subtle' },
        { word: 'Highkey', hint: 'Obviously' },
        { word: 'Caught in 4K', hint: 'Exposed' },
        { word: 'Touch Grass', hint: 'Outside' },
        { word: 'L + Ratio', hint: 'Roast' },
        { word: 'Based', hint: 'Bold' },
        { word: 'Copium', hint: 'Cope' },
        { word: 'Aura', hint: 'Points' },
        { word: 'Mog', hint: 'Dominate' },
        { word: 'Looksmaxxing', hint: 'Glow up' },
        { word: 'Oomfie', hint: 'Mutual' },
        { word: 'Bop', hint: 'Banger' },
        { word: 'Sus', hint: 'Suspicious' },
        { word: 'Ghosting', hint: 'Disappear' },
        { word: 'Parasocial', hint: 'One-sided' },
        { word: 'Unhinged', hint: 'Chaotic' },
        { word: 'Roman Empire', hint: 'Think about' }
      ]
    },
    internet: {
      name: 'Internet & Memes',
      words: [
        { word: 'Rickroll', hint: 'Never gonna' },
        { word: 'Doomscrolling', hint: 'Feed' },
        { word: 'Ratio', hint: 'Reply' },
        { word: 'Cancel Culture', hint: 'Boycott' },
        { word: 'Influencer', hint: 'Follower' },
        { word: 'Clout', hint: 'Fame' },
        { word: 'Stan', hint: 'Fan' },
        { word: 'FOMO', hint: 'Missing out' },
        { word: 'Catfish', hint: 'Fake' },
        { word: 'Troll', hint: 'Bait' },
        { word: 'Clickbait', hint: 'Title' },
        { word: 'Viral', hint: 'Spread' },
        { word: 'Karen', hint: 'Manager' },
        { word: 'Florida Man', hint: 'Headlines' },
        { word: 'Shitpost', hint: 'Chaos' },
        { word: 'Copypasta', hint: 'Paste' },
        { word: 'Stonks', hint: 'Profit' },
        { word: 'Wojak', hint: 'Feels' },
        { word: 'Pepe', hint: 'Frog' },
        { word: 'Doge', hint: 'Wow' },
        { word: 'Amogus', hint: 'Vent' },
        { word: 'POV', hint: 'Point of view' },
        { word: 'ASMR', hint: 'Tingle' },
        { word: 'Mukbang', hint: 'Eating' },
        { word: 'Speedrun', hint: 'Fast' },
        { word: 'Rage Bait', hint: 'Angry' },
        { word: 'Deep Fried Meme', hint: 'Crispy' },
        { word: 'Hot Take', hint: 'Opinion' },
        { word: 'Lore', hint: 'Backstory' },
        { word: 'AFK', hint: 'Away' }
      ]
    },
    fashion: {
      name: 'Fashion & Style',
      words: [
        { word: 'Sneakers', hint: 'Sole' },
        { word: 'Hoodie', hint: 'Hood' },
        { word: 'Windbreaker', hint: 'Nylon' },
        { word: 'Denim', hint: 'Jeans' },
        { word: 'Flannel', hint: 'Plaid' },
        { word: 'Crocs', hint: 'Jibbitz' },
        { word: 'Tie-Dye', hint: 'Hippie' },
        { word: 'Bucket Hat', hint: 'Fisherman' },
        { word: 'Choker', hint: 'Neck' },
        { word: 'Fanny Pack', hint: 'Waist' },
        { word: 'Platform Shoes', hint: 'Tall' },
        { word: 'Beanie', hint: 'Winter' },
        { word: 'Leather Jacket', hint: 'Biker' },
        { word: 'Overalls', hint: 'Farmer' },
        { word: 'Turtleneck', hint: 'Steve Jobs' },
        { word: 'Hawaiian Shirt', hint: 'Tropical' },
        { word: 'Cargo Pants', hint: 'Pockets' },
        { word: 'Uggs', hint: 'Cozy' },
        { word: 'Birkenstocks', hint: 'Cork' },
        { word: 'Scrunchie', hint: 'Hair' },
        { word: 'Athleisure', hint: 'Gym' },
        { word: 'Vintage', hint: 'Thrift' },
        { word: 'Corset', hint: 'Lace' },
        { word: 'Jumpsuit', hint: 'One piece' },
        { word: 'Mom Jeans', hint: 'High waist' },
        { word: 'Mullet', hint: 'Business' },
        { word: 'Man Bun', hint: 'Knot' },
        { word: 'Acrylic Nails', hint: 'Long' },
        { word: 'Face Tattoo', hint: 'Bold' },
        { word: 'Drip', hint: 'Outfit' }
      ]
    }
  };

  // Custom packs loaded from storage, keyed by "custom_<index>"
  let customPacks = {};

  function loadCustomPacks(packs) {
    customPacks = {};
    if (!packs || !packs.length) return;
    packs.forEach((pack, i) => {
      const id = 'custom_' + i;
      customPacks[id] = {
        name: pack.name,
        words: pack.words // each: { word, hint }
      };
    });
  }

  function getCategories() {
    const built = Object.keys(data).map(id => ({
      id,
      name: data[id].name,
      count: data[id].words.length,
      custom: false
    }));
    const custom = Object.keys(customPacks).map(id => ({
      id,
      name: customPacks[id].name,
      count: customPacks[id].words.length,
      custom: true
    }));
    return built.concat(custom);
  }

  function getAllData() {
    return { ...data, ...customPacks };
  }

  function getRandomWord(categoryIds, usedWords) {
    const all = getAllData();
    const pool = [];
    const ids = categoryIds && categoryIds.length > 0
      ? categoryIds
      : Object.keys(all);

    ids.forEach(id => {
      if (!all[id]) return;
      all[id].words.forEach(w => {
        pool.push({ ...w, category: all[id].name });
      });
    });

    // Filter out recently used words
    const used = usedWords || [];
    let available = pool.filter(w => !used.includes(w.word));

    // If all used, reset
    if (available.length === 0) {
      available = pool;
    }

    // Pick random
    const pick = available[Math.floor(Math.random() * available.length)];
    return pick;
  }

  function getTotalWordCount() {
    const all = getAllData();
    let count = 0;
    Object.values(all).forEach(cat => { count += cat.words.length; });
    return count;
  }

  return { getCategories, getRandomWord, getTotalWordCount, loadCustomPacks };
})();

// Node.js compat for testing
if (typeof module !== 'undefined') module.exports = Words;
